# Generated by Django 5.0.4 on 2024-04-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Золото+', 'gold'), ('Платина', 'platinum'), ('VIP', 'vip')], max_length=10, null=True)),
                ('code_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.codenumber')),
            ],
        ),
    ]
