# Generated by Django 5.0.4 on 2024-04-23 13:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=22, verbose_name='Недели Месяцы')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('image', models.ImageField(upload_to='', verbose_name='Флаг Страны')),
            ],
        ),
        migrations.CreateModel(
            name='RoamingAddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описания подробности')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('calls', ckeditor.fields.RichTextField(verbose_name='Звонки')),
                ('sms', ckeditor.fields.RichTextField(verbose_name='SMS')),
                ('it_works', models.CharField(max_length=40, verbose_name='Действует')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('ussd_code', models.CharField(max_length=10, verbose_name='USSD-код: Подключении')),
                ('country_international_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.country', verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('gigabytes', ckeditor.fields.RichTextField(verbose_name='Гигабайты')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архивировать')),
                ('international_challenges', models.TextField(blank=True, null=True, verbose_name='Международные вызовы')),
                ('ussd_code', models.CharField(max_length=10, verbose_name=' USSD-код: Подключении')),
                ('category_service_tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categoryrate', verbose_name='Недели Месяцы')),
            ],
        ),
        migrations.CreateModel(
            name='ContinueRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_sms', models.CharField(choices=[('Обычный SMS', 'usual_call'), ('Обычный Звонки', 'usual_sms'), ('Доп. Звонки', 'call'), ('Доп. SMS', 'sms')], max_length=100, verbose_name='Звонки и SMS')),
                ('rich_rate', ckeditor.fields.RichTextField(verbose_name='Звонки или SMS')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_rate', to='app1.rate', verbose_name='Тариф')),
            ],
        ),
        migrations.CreateModel(
            name='Roaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('gigabytes', ckeditor.fields.RichTextField(verbose_name='Гигабайты')),
                ('minutes', ckeditor.fields.RichTextField(verbose_name='Звонки')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('it_works', models.CharField(max_length=50, verbose_name='Действует')),
                ('ussd_code', models.CharField(max_length=10, verbose_name='USSD-код: Подключении')),
                ('country_roaming', models.ManyToManyField(to='app1.country', verbose_name='Стран Действия')),
            ],
        ),
        migrations.CreateModel(
            name='RoamingBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('gigabytes', ckeditor.fields.RichTextField(verbose_name='Гигабайты')),
                ('minutes', ckeditor.fields.RichTextField(verbose_name='Звонки')),
                ('ussd_code', models.CharField(max_length=10, verbose_name='USSD-код: Подключении')),
                ('country_roaming_business', models.ManyToManyField(to='app1.country', verbose_name='Стран Действия')),
            ],
        ),
        migrations.CreateModel(
            name='NextRoamingBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sms_balance', models.CharField(choices=[('Исходящие звонки в роуминге', 'call'), ('Исходящие SMS в роуминге', 'sms'), ('При недостатке средств на балансе:', 'balance')], max_length=100, verbose_name='Звонки SMS Баланс')),
                ('rich_roaming_business', ckeditor.fields.RichTextField(verbose_name='Звонки или SMS или Баланс')),
                ('roaming_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequels_roaming', to='app1.roamingbusiness', verbose_name='Роуминг Бизнес')),
            ],
        ),
    ]
