# Generated by Django 5.0.4 on 2024-04-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roamingaddinfo',
            name='roaming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.roaming'),
        ),
    ]
