# Generated by Django 5.0.4 on 2024-04-25 18:09

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_roamingaddinfo_roaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='category_service_tariff',
        ),
        migrations.AddField(
            model_name='rate',
            name='it_work',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Недели Месяцы'),
        ),
        migrations.AlterField(
            model_name='continuerate',
            name='calls_sms',
            field=models.CharField(choices=[('Обычный SMS', 'usual_call'), ('Обычный Звонки', 'usual_sms'), ('Доп. Звонки', 'call'), ('Доп. SMS', 'sms')], max_length=100, null=True, verbose_name='Звонки и SMS'),
        ),
        migrations.AlterField(
            model_name='continuerate',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continue_rate', to='app1.rate', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='continuerate',
            name='rich_rate',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Звонки или SMS'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Флаг Страны'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='calls',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Звонки'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='country_international_comm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='it_works',
            field=models.CharField(max_length=40, null=True, verbose_name='Действует'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='sms',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='SMS'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internationalcommunication',
            name='ussd_code',
            field=models.CharField(max_length=10, null=True, verbose_name='USSD-код: Подключении'),
        ),
        migrations.AlterField(
            model_name='nextroamingbusiness',
            name='call_sms_balance',
            field=models.CharField(choices=[('Исходящие звонки в роуминге', 'call'), ('Исходящие SMS в роуминге', 'sms'), ('При недостатке средств на балансе:', 'balance')], max_length=100, null=True, verbose_name='Звонки SMS Баланс'),
        ),
        migrations.AlterField(
            model_name='nextroamingbusiness',
            name='rich_roaming_business',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Звонки или SMS или Баланс'),
        ),
        migrations.AlterField(
            model_name='nextroamingbusiness',
            name='roaming_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequels_roaming', to='app1.roamingbusiness', verbose_name='Роуминг Бизнес'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='gigabytes',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Гигабайты'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='is_archive',
            field=models.BooleanField(default=False, null=True, verbose_name='Архивировать'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ussd_code',
            field=models.CharField(max_length=10, null=True, verbose_name=' USSD-код: Подключении'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='country_roaming',
            field=models.ManyToManyField(null=True, to='app1.country', verbose_name='Стран Действия'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='gigabytes',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Гигабайты'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='it_works',
            field=models.CharField(max_length=50, null=True, verbose_name='Действует'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='minutes',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Звонки'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roaming',
            name='ussd_code',
            field=models.CharField(max_length=10, null=True, verbose_name='USSD-код: Подключении'),
        ),
        migrations.AlterField(
            model_name='roamingaddinfo',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описания подробности'),
        ),
        migrations.AlterField(
            model_name='roamingaddinfo',
            name='name',
            field=models.CharField(max_length=54, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roamingbusiness',
            name='country_roaming_business',
            field=models.ManyToManyField(null=True, to='app1.country', verbose_name='Стран Действия'),
        ),
        migrations.AlterField(
            model_name='roamingbusiness',
            name='gigabytes',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Гигабайты'),
        ),
        migrations.AlterField(
            model_name='roamingbusiness',
            name='minutes',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Звонки'),
        ),
        migrations.AlterField(
            model_name='roamingbusiness',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roamingbusiness',
            name='ussd_code',
            field=models.CharField(max_length=10, null=True, verbose_name='USSD-код: Подключении'),
        ),
        migrations.DeleteModel(
            name='CategoryRate',
        ),
    ]
