# Generated by Django 5.0.4 on 2024-04-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_rate_category_service_tariff_rate_it_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
