# Generated by Django 5.0.4 on 2024-04-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_rate_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('full_description', models.TextField(null=True)),
                ('video', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ContinueEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_tech_spec', models.CharField(choices=[('Варианты приобретения', 'purchase options'), ('Технические характеристики', 'technical specifications')], max_length=100, null=True, verbose_name='Вар оплаты или Тех хар')),
                ('text', models.CharField(max_length=155, null=True)),
                ('technical', models.CharField(max_length=100, null=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.equipment')),
            ],
        ),
    ]
