# Generated by Django 5.0.4 on 2024-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_equipment_continueequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continueequipment',
            name='technical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
