# Generated by Django 5.0.4 on 2024-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_continueequipment_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continueequipment',
            name='technical',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
